### PR TITLE
Lwt 4.0.0, 4.0.1, 4.1.0

### PR DESCRIPTION
**Pull request by aantron**
cc @balat. This also makes `dev` a copy of `4.1.0` (instead of `3.2.1`). I think this will need a site update, and a change so that 4.1.0 is selected by default from the version drop-down.

### CODE REVIEW

**Comment by balat** [comment]
I just updated the Web site. Tell me if it's ok for you.

Vincent

**Comment by aantron** [comment]
Thanks, the new versions are up and look correct.

The default version displayed is still 3.2.1, however, when visiting https://ocsigen.org/lwt/

**Comment by balat** [comment]
Ok. Should be fixed now.

**Comment by aantron** [comment]
Still seeing 3.2.1 selected initially when visiting https://ocsigen.org/lwt/. I cleared the browser cache to be sure.

**Pull request merged**
