### PR TITLE
Lwt 3.3.0

### PR DESCRIPTION
**Pull request by aantron**
Trying adding Lwt docs manually. If it works, I'll add the rest of the recent versions, and set dev to 4.1.0.

### CODE REVIEW

**Comment by aantron** [comment]
Looks like I can merge this myself.

**Comment by aantron** [comment]
@balat What needs to be done after merging this PR, to get the docs to be updated online?

**Comment by balat** [comment]
Hello,
I need to regenerate the Web site myself. We had some problems with html_of_wiki but we will finally have someone working on it very shortly (and you'll be able to use it yourself very simply to generate gh-pages).
I'll try to regenerate the documentation before tomorrow evening.
Vincent

**Comment by balat** [comment]
cc @leovalais

**Comment by balat** [comment]
@aantron The site is now updated. Can you check?

**Comment by aantron** [comment]
Thanks, looks like it's up. The only thing is that the default version selected is still 3.2.1, and one has to manually choose 3.3.0 from the drop-down. This isn't worth fixing right now. Let me upload all the new docs up to 4.1.0, and I'll ping about addressing the default version in that PR.

**Pull request merged**
