### PR TITLE
fix spelling of "versioned"

### PR DESCRIPTION
**Pull request by agarwal**
Please also fix in the project's GitHub description.

### CODE REVIEW

**Comment by vasilisp** [comment]
Thanks!

**Comment by vasilisp** [comment]
@drup can you fix the description? I don't have the needed permissions.

**Comment by dannywillems** [comment]
About permissions, it seems it is since the new GitHub version (last week).

**Comment by Drup** [comment]
Done. Not sure why you can't change the description, you should have the necessary rights ...

**Comment by dannywillems** [comment]
@Drup GitHub changes recently the rights about members in organizations. `Members` can not edit title but `Owners` can. I think it's this link: https://help.github.com/articles/permission-levels-for-an-organization/.

**Pull request merged**
